---
name: Poblaria Deployment
run-name: "[Deploy] ${{ github.event.head_commit.message || github.ref_name }}"

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  DEPLOY_PATH: ~/apps/poblaria

jobs:
  create-docker-tag:
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.docker-tag.outputs.docker-tag }}

    steps:
      - name: Create Docker tag
        id: docker-tag
        run: echo "docker-tag=$(date +%s)" >> $GITHUB_OUTPUT

  build-push-image:
    runs-on: ubuntu-latest
    needs: create-docker-tag
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        project: [ backend, frontend ]

    steps:
      - uses: actions/checkout@v5

      - name: Build the Docker image
        run: docker build . --file apps/${{ matrix.project }}/Dockerfile  --tag ghcr.io/poblaria/${{ matrix.project }}:${{ needs.create-docker-tag.outputs.docker-tag }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image to the GitHub registry
        run: docker push ghcr.io/poblaria/${{ matrix.project }}:${{ needs.create-docker-tag.outputs.docker-tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ create-docker-tag, build-push-image ]

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add remote server to known_hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # TODO: must Docker Compose be on remote server, way to do it different?
      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd ${{ env.DEPLOY_PATH }}
            sed -i 's/^DOCKER_TAG=.*/DOCKER_TAG=${{ needs.create-docker-tag.outputs.docker-tag }}/' .env
            docker compose up -d
          EOF

      - name: Cleanup SSH
        if: always()
        run: rm -f ~/.ssh/deploy_key
