---
name: Poblaria
run-name: "[Poblaria] ${{ github.event.head_commit.message }}"
permissions:
  contents: read

on:
  push:

jobs:
  lint:
    name: Lint and check files format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [ backend, frontend ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        working-directory: apps/${{ matrix.project }}
        run: npm run lint

      - name: Check files format
        working-directory: apps/${{ matrix.project }}
        run: npm run format:check

  typecheck:
    name: Check types
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [ backend, frontend ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check types
        working-directory: apps/${{ matrix.project }}
        run: npm run typecheck

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [ lint, typecheck ]
    defaults:
      run:
        working-directory: apps/backend

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: npm test

  build:
    name: Build projects
    runs-on: ubuntu-latest
    needs: [ lint, typecheck ]
    strategy:
      fail-fast: false
      matrix:
        project: [ backend, frontend ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build project
        working-directory: apps/${{ matrix.project }}
        run: npm run build
